Traceback (most recent call last):
  File "/home/repos/ocean/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/repos/ocean/manage.py", line 22, in <module>
    main()
  File "/home/repos/ocean/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W002) Your URL pattern '/article/<title>' [name='article'] has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.

System check identified 1 issue (0 silenced).
Performing system checks...

July 07, 2022 - 12:37:55
Django version 4.0.5, using settings 'ocean.settings'
Starting development server at http://192.168.2.60:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/home/repos/ocean/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/repos/ocean/manage.py", line 22, in <module>
    main()
  File "/home/repos/ocean/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/repos/ocean/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/repos/ocean/manage.py", line 22, in <module>
    main()
  File "/home/repos/ocean/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
